version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
      - "/agent"
      - "/core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
