// ISO 3166-1 alpha-2 country codes, which is the granularity the WAF's region
// access control works at.
//
// Only the CODES are hard-coded here. Display names come from the browser's own
// Intl.DisplayNames, so both the Chinese and English names are correct and stay
// correct without this file carrying a translation table that would drift.
const CODES = [
    'AD',
    'AE',
    'AF',
    'AG',
    'AI',
    'AL',
    'AM',
    'AO',
    'AQ',
    'AR',
    'AS',
    'AT',
    'AU',
    'AW',
    'AX',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BL',
    'BM',
    'BN',
    'BO',
    'BQ',
    'BR',
    'BS',
    'BT',
    'BV',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CC',
    'CD',
    'CF',
    'CG',
    'CH',
    'CI',
    'CK',
    'CL',
    'CM',
    'CN',
    'CO',
    'CR',
    'CU',
    'CV',
    'CW',
    'CX',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'EH',
    'ER',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FK',
    'FM',
    'FO',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GF',
    'GG',
    'GH',
    'GI',
    'GL',
    'GM',
    'GN',
    'GP',
    'GQ',
    'GR',
    'GS',
    'GT',
    'GU',
    'GW',
    'GY',
    'HK',
    'HM',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IM',
    'IN',
    'IO',
    'IQ',
    'IR',
    'IS',
    'IT',
    'JE',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KP',
    'KR',
    'KW',
    'KY',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MF',
    'MG',
    'MH',
    'MK',
    'ML',
    'MM',
    'MN',
    'MO',
    'MP',
    'MQ',
    'MR',
    'MS',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NC',
    'NE',
    'NF',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NU',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PF',
    'PG',
    'PH',
    'PK',
    'PL',
    'PM',
    'PN',
    'PR',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RE',
    'RO',
    'RS',
    'RU',
    'RW',
    'SA',
    'SB',
    'SC',
    'SD',
    'SE',
    'SG',
    'SH',
    'SI',
    'SJ',
    'SK',
    'SL',
    'SM',
    'SN',
    'SO',
    'SR',
    'SS',
    'ST',
    'SV',
    'SX',
    'SY',
    'SZ',
    'TC',
    'TD',
    'TF',
    'TG',
    'TH',
    'TJ',
    'TK',
    'TL',
    'TM',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'UM',
    'US',
    'UY',
    'UZ',
    'VA',
    'VC',
    'VE',
    'VG',
    'VI',
    'VN',
    'VU',
    'WF',
    'WS',
    'YE',
    'YT',
    'ZA',
    'ZM',
    'ZW',
];

export interface Country {
    code: string;
    zh: string;
    en: string;
}

// These four are pinned rather than taken from the browser.
//
// Two reasons, both concrete. Intl.DisplayNames wording for TW/HK/MO varies with
// the browser's ICU version, so the same panel would read differently on two
// machines. And the address database treats CN, HK, MO and TW as four separate
// entries, so an operator picking "中国大陆" must be able to see that Hong Kong,
// Macau and Taiwan are separately selectable rather than assume they are covered.
const PINNED: Record<string, { zh: string; en: string }> = {
    CN: { zh: '中国大陆', en: 'Chinese mainland' },
    HK: { zh: '中国香港', en: 'Hong Kong, China' },
    MO: { zh: '中国澳门', en: 'Macao, China' },
    TW: { zh: '中国台湾', en: 'Taiwan, China' },
};

// PINNED_ORDER is listed first, matching how the four appear at the top of the
// upstream product's picker.
const PINNED_ORDER = ['CN', 'HK', 'MO', 'TW'];

// Intl.DisplayNames is available in every browser this panel supports, but a
// failure here must not take the whole page down — the code itself is a usable
// label, just a less friendly one.
const displayName = (locale: string) => {
    try {
        const names = new Intl.DisplayNames([locale], { type: 'region' });
        return (code: string) => names.of(code) || code;
    } catch {
        return (code: string) => code;
    }
};

const zhName = displayName('zh-CN');
const enName = displayName('en');

const resolve = (code: string): Country => {
    const pinned = PINNED[code];
    return {
        code,
        zh: pinned ? pinned.zh : zhName(code),
        en: pinned ? pinned.en : enName(code),
    };
};

// The pinned four first, then everything else sorted by its Chinese name — the
// order an operator scanning the list expects, and the one the upstream product
// uses.
const rest = CODES.filter((code) => !PINNED_ORDER.includes(code))
    .map(resolve)
    .sort((a, b) => a.zh.localeCompare(b.zh, 'zh-Hans-CN'));

export const COUNTRIES: Country[] = [...PINNED_ORDER.map(resolve), ...rest];
